name: "Python 3.7"

on:
    push:
    pull_request:

jobs:
    test:
        runs-on: ubuntu-20.04
        name: "Tests"
        steps:
            - uses: actions/checkout@v2
            - name: Set up python 3.7 
              uses: actions/setup-python@v2
              with:
                  python-version: "3.7"
            - name: install dependencies
              run: |
                  sudo apt update
                  sudo apt install graphviz imagemagick x11-apps xserver-xephyr xterm xvfb libpulse-dev lm-sensors
                  pip install nox
            - name: test
              env:
                  NOXENV: "3.7"
              run: nox -s test
